### ISSUE TITLE
Linked addon unavailable.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [117649/Tab-Groups#4]
https://addons.mozilla.org/firefox/addon/tab-groups-panorama/ doesn't exist.

**Comment by 117649** [comment]
Not related to this repo. Not my problem.

**Comment by beedell-roke** [comment]
Then why is it linked by your repo?

![image](https://user-images.githubusercontent.com/42837531/222423837-26ce7af2-0dac-48d5-80c2-246f3f1319af.png)

**Comment by 117649** [comment]
> Then why is it linked by your repo?
> 

You know what a fork is?

**Comment by beedell-roke** [comment]
@117649, yes. Why do you ask?

**Comment by 117649** [comment]
> @117649, yes. Why do you ask?

No you don't obviously.

This is my fork I only make change that I want to make and I don't give any shit about what a stupid link from original repo goes where.
